<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();
?>
<div id="quick-order-modal-content" style="display: none;">
    <form id="quick-order-form">
        <div class="fieldset">
            <div class="field">
                <strong><?= __('Product Name: ') ?></strong>
                <span id="product-name"></span>
            </div>
            <div class="field">
                <label class="label"><?= __('Name') ?></label>
                <input type="text" name="name">
            </div>
            <div class="field _required">
                <label class="label"><?= __('Phone Number') ?></label>
                <input type="text" name="phone">
            </div>
            <div class="field">
                <label class="label"><?= __('Comment') ?></label>
                <textarea name="comment"></textarea>
            </div>
            <div class="field">
                <span id="quick-order-note">Менеджер работает с 9 до 19-ти и свяжется с Вами в течение 4-х рабочих часов.</span>
            </div>
            <div class="field">
                <button type="submit" class="action primary"><?= __('Submit') ?></button>
            </div>
        </div>
    </form>
</div>

<?php foreach ($block->getChildNames() as $childName) : ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
        <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()) : ?>
            <div class="field qty">
                <label class="label" for="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div class="control">
                    <input type="number" data-role="qty" id="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" class="input-text qty" data-validate="{'required-number':true,'validate-greater-than-zero':true, 'validate-item-quantity':{'minAllowed':<?= /* @noEscape */ $allowedQty['minAllowed'] ?>,'maxAllowed':<?= /* @noEscape */ $allowedQty['maxAllowed'] ?>}}"
                           name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" value="<?= /* @noEscape */ $block->getAddToCartQty($item) * 1 ?>" <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?>>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($product->isSaleable()) : ?>
            <div class="product-item-actions">
                <div class="actions-primary">
                    <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                    </button>
                    <button
                        type="button"
                        title="<?= __('Quick order') ?>"
                        class="tocart primary quick-order"
                        data-mage-init='{"quick-order-modal": {"target": "#quick-order-modal-content", "productName": "<?= $product->getName() ?>"}}'>
                        <span><?= __('Quick order') ?></span>
                    </button>
                </div>
            </div>
        <?php else : ?>
            <?php if ($product->getIsSalable()) : ?>
                <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                </p>
            <?php else : ?>
                <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </fieldset>
</div>
